### ISSUE TITLE
OCL Library Clash Error

### ISSUE THREAD

**Issue by brittanyfriedland** [Open-MBEE/mdk#20]
I am using version 2.1 and I am getting the following error when I try to validate views that use custom "TableExpressionColumn"s in my viewpoint diagram. 

For example when I try to recreate this diagram from the user guide, i receive the error message below:
![capture1](https://cloud.githubusercontent.com/assets/13018689/9282438/4182664e-4281-11e5-8b30-43bf61aeee00.JPG)

Here is the error message:

java.lang.NoSuchMethodError: org.eclipse.ocl.ecore.EcoreEvaluationEnvironment.<init>(Lorg/eclipse/ocl/ecore/EcoreEnvironmentFactory;)V
    at gov.nasa.jpl.ocl.DgEvaluationEnvironment.<init>(DgEvaluationEnvironment.java:65)
    at gov.nasa.jpl.ocl.DgEnvironmentFactory.createEvaluationEnvironment(DgEnvironmentFactory.java:101)
    at gov.nasa.jpl.ocl.DgEnvironmentFactory.getDgEvaluationEnvironment(DgEnvironmentFactory.java:123)
    at gov.nasa.jpl.ocl.OclEvaluator.addRegexMatchOperation(OclEvaluator.java:489)
    at gov.nasa.jpl.ocl.OclEvaluator.setupEnvironment(OclEvaluator.java:957)
    at gov.nasa.jpl.ocl.OclEvaluator.evaluateQuery(OclEvaluator.java:354)
    at gov.nasa.jpl.ocl.OclEvaluator.evaluateQuery(OclEvaluator.java:284)
    at gov.nasa.jpl.ocl.OclEvaluator.evaluateQuery(OclEvaluator.java:267)
    at gov.nasa.jpl.mbee.generator.DocumentValidator.evaluate(DocumentValidator.java:767)
    at gov.nasa.jpl.mbee.generator.DocumentValidator.evaluate(DocumentValidator.java:747)
    at gov.nasa.jpl.mbee.model.TableStructure.buildTableReferences(TableStructure.java:293)
    at gov.nasa.jpl.mbee.model.TableStructure.visit(TableStructure.java:326)
    at gov.nasa.jpl.mbee.model.DocBookOutputVisitor.visit(DocBookOutputVisitor.java:65)
    at gov.nasa.jpl.mbee.model.Query.accept(Query.java:129)
    at gov.nasa.jpl.mbee.model.AbstractModelVisitor.visitChildren(AbstractModelVisitor.java:51)
    at gov.nasa.jpl.mbee.model.DocBookOutputVisitor.visit(DocBookOutputVisitor.java:126)
    at gov.nasa.jpl.mbee.model.Section.accept(Section.java:99)
    at gov.nasa.jpl.mbee.model.AbstractModelVisitor.visitChildren(AbstractModelVisitor.java:51)
    at gov.nasa.jpl.mbee.model.DocBookOutputVisitor.visit(DocBookOutputVisitor.java:99)
    at gov.nasa.jpl.mbee.model.Document.accept(Document.java:379)
    at gov.nasa.jpl.mbee.ems.validation.ViewValidator.validate(ViewValidator.java:168)
    at gov.nasa.jpl.mbee.ems.ValidateViewRunner.run(ValidateViewRunner.java:53)
    at com.nomagic.ui.BaseProgressMonitor$ProgressTask.execute(BaseProgressMonitor.java:1143)
    at com.nomagic.task.Task.construct(Task.java:196)
    at com.nomagic.task.SwingWorker$3.call(SwingWorker.java:219)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at com.nomagic.task.SwingWorker$SwingWorkerFuture.run(SwingWorker.java:608)
    at com.nomagic.task.BackportedThreadPoolExecutor$Worker.runTask(BackportedThreadPoolExecutor.java:1581)
    at com.nomagic.task.BackportedThreadPoolExecutor$Worker.run(BackportedThreadPoolExecutor.java:1612)
    at com.nomagic.task.PooledThread.run(PooledThread.java:64)

**Comment by Enquier** [comment]
This should be fixed by cgaley's commit:
b7ce4c10f35241b0689ade56830bcf3411611b4a

**Comment by brittanyfriedland** [comment]
unfortunately, it didn't work :-(
