### ISSUE TITLE
MDK fails to add org/project in Cameo 19.

### ISSUE THREAD

**Issue by sand7000** [Open-MBEE/mdk#260]
I am using:
MMS Release 4.0.18
View Editor (VE) Release 4.0.2
MDK Release 5.1.3
Cameo 19 SP4

Test Results
    * Plugin installs and loads
    * MMS Menus and options visible
    * Logs in to MMS
    * Model Validation Runs
    * Attempt to add project to MMS generates internal Cameo Error 

Log text below and test model attached:

[test.zip](https://github.com/Open-MBEE/mdk/files/11761081/test.zip)

```
Thu Jun 15 13:25:29 EDT 2023
Error count: 2
org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed. (Caused by org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.) (Caused by org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed. (Caused by org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.))
	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:543)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:235)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:209)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:351)
	at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:72)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:955)
	at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:58)
	at gov.nasa.jpl.mbee.mdk.mms.MMSUtils.sendMMSRequest(MMSUtils.java:235)
	at gov.nasa.jpl.mbee.mdk.mms.MMSUtils.sendMMSRequest(MMSUtils.java:314)
	at gov.nasa.jpl.mbee.mdk.mms.MMSUtils.getMmsOrg(MMSUtils.java:372)
	at gov.nasa.jpl.mbee.mdk.mms.actions.CommitProjectAction.commitAction(CommitProjectAction.java:77)
	at gov.nasa.jpl.mbee.mdk.mms.actions.CommitProjectAction.actionPerformed(CommitProjectAction.java:68)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:882)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:926)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at com.nomagic.utils.EventTracker.dispatchEvent(EventTracker.java:31)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed. (Caused by org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.)
	at org.apache.commons.logging.impl.LogFactoryImpl.getLogConstructor(LogFactoryImpl.java:397)
	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:529)
	... 50 more
Caused by: org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.
	at org.apache.commons.logging.impl.LogFactoryImpl.getLogConstructor(LogFactoryImpl.java:385)
	... 51 more

User information:
    Registered to: ADVENTIUM LABS
    Profile: 688697
    Key ID: LKO2022406_55582
System information:
    JVM:
        Name: OpenJDK 64-Bit Server VM;
        Version: 1.8.0_362;
        Vendor: Private Build;
    OS:
        Name: Linux;
        Architecture: amd64;
        Version: 5.15.0-73-generic;
        Locale: English;
MagicDraw Version:
Cameo Enterprise Architecture 19.0 SP4
Version: Commercial with expiration
Edition: Enterprise
License: Floating
Build: 20200314_0955-ae099fab
Registered to: ADVENTIUM LABS
Expires at: May 10, 2024

Cameo Business Modeler 19.0 SP4 Plugin
Version: Evaluation
Build: 20200314_0748-ae099fab
Expires at: May 10, 2024

Cameo Concept Modeler 19.0 SP4 Plugin
Version: Evaluation
Build: 20200303_1229-f28c8930
Expires at: May 10, 2024

Cameo Data Modeler 19.0 SP4 Plugin
Version: Evaluation
Build: 20200314_0711-ae099fab
Expires at: May 10, 2024

Cameo Requirements Modeler 19.0 SP4 Plugin
Version: Evaluation
Build: 20200314_0715-ae099fab
Expires at: May 10, 2024

Merge 19.0 SP4 Plugin
Version: Commercial with expiration
Build: 20200314_0955-ae099fab
Expires at: May 10, 2024

SysML 19.0 SP4 Plugin
Version: Evaluation
Build: 20200314_0744-ae099fab
Expires at: May 10, 2024

UAF 19.0 SP4 Plugin
Version: Evaluation
Build: 20200314_0814-ae099fab
Expires at: May 10, 2024

AutoStyler 19.0 SP4
Enterprise Architect Import 19.0 SP4
Strict UML XMI Exporter 17.0 SP2
TOGAF 19.0 SP4
Zachman Framework 19.0 SP1

Third Party Plugins:
Model Development Kit 5.1.3 (OpenMBEE)

MagicDraw Environment
Installed at: /home/esandberg/19-cameo/
Configuration files: /home/esandberg/.cameoea/19.0/
```

**Comment by dlamoris** [comment]
can you try moving {cameoinstall}/plugins/gov.nasa.jpl.cae.magicdraw.mdk/commons-logging-1.2.jar somewhere else? It may be conflicting with some other plugin or native cameo library
Has the plugin worked for you before? If it did, do you remember if anything about your environment changed?

**Comment by sand7000** [comment]
> can you try moving {cameoinstall}/plugins/gov.nasa.jpl.cae.magicdraw.mdk/commons-logging-1.2.jar somewhere else?

It tried that and I still get the same exact internal error. I search the plugins dir and found two other copies of commons-logging-1.x.jar and moved them as well. Still get the same exact error.

> Has the plugin worked for you before? If it did, do you remember if anything about your environment changed?

This is a fresh install of cameo 19 sp4, purely for trying to learn more about openmbee. I have installed no other plugins.

**Comment by sand7000** [comment]
Oh and to be clear I exited cameo moved those jars and then restarted cameo to make sure it was reloading everything fresh.

**Comment by dlamoris** [comment]
Do you happen to have access to cameo systems modeler sp3? That's the cameo product that's being used internally - I would think the plugin should work for any cameo 19 product or sp (i see you have cameo enterprise architecture sp4), but maybe there's some differences that's causing the error. I think systems modeler is basically the same as magicdraw with sysml plugin. Cameo systems modeler is the only version I have access to for dev/test unfortunately

**Comment by sand7000** [comment]
I made a clean Ubuntu 20 VM and installed Cameo Enterprise Architect 19 SP3. I made a new test model and I get the same error.

Seems like the MDK doesn't work with Cameo Enterprise Architect. Might need to revise the compatibility matrix. 

I don't have Cameo Systems Modeler so I will try MagicDraw next and update this ticket with the results.

**Comment by sand7000** [comment]
Magicdraw 19 sp3 works as expected.

Thanks so much for all your help!
